### ISSUE TITLE
ランク帯表示する機能の追加

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#1]
**内容**
LoLの募集はEnjoy勢（ランク関係なし）と、ある程度のランク帯で集まってやりたい人がいると思うので、ランク帯を募集フォームから任意選択出来て、後からランク帯別の募集を見れると嬉しいかも。

**ランク帯種別**

- UnRank
- Iron
- Bronze
- Silver
- Gold
- Platina
- Diamond
- Master
- Grand Master
- Challenger

**Comment by yuko-okayasu** [comment]
Table
| id | name |
| -- | -- |
| id | ランク名 |

**Comment by rutko** [comment]
![9-1](https://user-images.githubusercontent.com/26114407/78145520-f3461300-746b-11ea-9b9a-6beb289f8d2e.png)
![8-1](https://user-images.githubusercontent.com/26114407/78145551-fe993e80-746b-11ea-9efa-ea8f18272e65.png)
![7-1](https://user-images.githubusercontent.com/26114407/78145591-0953d380-746c-11ea-86a0-a9bc0647fa60.png)
![6-1](https://user-images.githubusercontent.com/26114407/78145620-0fe24b00-746c-11ea-9a56-f6aa16738cff.png)
![5-1](https://user-images.githubusercontent.com/26114407/78145672-1ffa2a80-746c-11ea-861f-a78e923b466c.png)
![4-1](https://user-images.githubusercontent.com/26114407/78145683-24264800-746c-11ea-9881-fc38a4370262.png)
![3-1](https://user-images.githubusercontent.com/26114407/78145726-32746400-746c-11ea-9e48-29787f6c7aed.png)
![2-1](https://user-images.githubusercontent.com/26114407/78145743-3902db80-746c-11ea-9f93-1df8d8c221f8.png)
![1-1](https://user-images.githubusercontent.com/26114407/78145772-4324da00-746c-11ea-9c80-cd6ad7c2b6b0.png)

**Comment by LeonTeraoka** [comment]
顔のアイコンばかりの投稿画面になりそうだね
対戦前のロード画面の如く、ランク帯別に投稿の枠が変わるようにするのは如何でしょうか

また、UnRankとは、「ランク外」の事？
それとも任意でランクを見せたくない人が選択する項目？
曖昧さ回避してほしいです

スペルミスもございましたので、下記ご参照頂ければ幸いです
・UnRanked
・Platinum

日本人向けのサイトであれば、わざわざ英語で表記する必要もなく、
上記に貼ってるアイコンをチェックできるようにすれば良いのでは？

ご確認の程、宜しくお願いいたします。
