### ISSUE TITLE
存在しないサモナー名の対応

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#139]
## Summary
存在するサモナー名を入力してくださいとかのアラートを出すようにする
## FYI

**Comment by LeonTeraoka** [comment]
How does your imagination look like?
Is it similar to the alert after the post?

**Comment by rutko** [comment]
投稿時に存在するサモナー名を入力してくださいとアラートを出して欲しい

**Comment by LeonTeraoka** [comment]
ok.
I'll come back on the 25th of Jan.
