### ISSUE TITLE
募集フォームの追加

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#2]
**内容**
フレンド募集フォームの作成

**必要フォーム**
- タグ
- 選択タグ
    - ゲーム種類
        - ノーマル
        - ランク
        - TFT
        - ハウリングアビス

    - ランク帯
    - champion種別
        - アサシン
        - サポート
        - タンク
        - ファイター 
        - マークスマン
        - メイジ 
- 名前
- 内容
- サモナー名 （任意入力可）
- SkypeID（任意入力可）
-  Discord ID（任意入力可）
- パスワード
- スパム確認（reCAPTCHA）

**必要機能**
- 投稿時間（何分前とか）
- 編集
- 削除（パスワード必須）

参考
https://disboard.org/ja
https://skypech.com/

**Comment by rutko** [comment]
必要であれば追加する機能
- 性別

**Comment by yuko-okayasu** [comment]
Table Team
| id | title | body | skype | discord | password | game_type | tag | rank_id |
| -- | ---- | ----- | ------ | ------- | ---------- | ----------- | --- | ------- |

**Comment by rutko** [comment]
**action** 

- `new`

- `edit `

- `delete`

**Comment by rutko** [comment]
@yuko-okayasu 
- model
- controller # action

@rutko 
- view

**Comment by rutko** [comment]
**追加**
チャンピオンの不向きがる為、よく使うチャンピオンの種類を選択できるようにする

- champion種別
    - アサシン
    - サポート
    - タンク
    - ファイター 
    - マークスマン
    - メイジ

**Comment by yuko-okayasu** [comment]
一つの募集フォームにタグを複数設定するのであれば、`Team`テーブルにカラムを作成するのではなくて、`Tag`テーブルを新たに用意して、中間テーブルとして`TeamTag`を作成するのが一番良さそう。

Tag
| id | tag |
| -- | --- |
| id | タグ名 |

TeamTag(中間テーブル)
| id | team_id | tag_id |
|-- | -------- | ------ |
| id | チームID | タグID |
