### ISSUE TITLE
サブタイトルをつける

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#45]
LoL-VCのサブタイトル、何にしよう☹

**Comment by hiro08gh** [comment]
LoLの友達が見つかる掲示板 - LoL-VC とか！？

**Comment by rutko** [comment]
コメント気づかなかった！
いいですね！！一旦それにします👍

**Comment by rutko** [comment]
![スクリーンショット 2020-07-02 0 26 10](https://user-images.githubusercontent.com/26114407/86262559-fed7e000-bbfa-11ea-8997-97a7af824727.png)

変更した！ @hiro08gh
