### ISSUE TITLE
投稿ページのレイアウト修正

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#71]
## 概要
投稿ページにて、レイアウトがずれてしまっているので修正したい。（おそらく原因はrutkoがi18n対応した時）

![スクリーンショット 2020-10-06 20 51 40](https://user-images.githubusercontent.com/26114407/95198229-dcff8200-0815-11eb-8d47-65666cd86a47.png)

## 変更内容

サモナー名を一番上に来るように設置し、次にランクのタイトル、その下をランクのチェックボックス、ゲームタイトルの下にチェックボックスにする（ゲームタイトルは段落をつける`/br`とかで合わせる）

並びとしては以下
- サモナーid
    - サモナー名フォーム

- ランク
    - ランクチェックボックス

- ゲーム
    - ゲームチェックボックス

**Comment by LeonTeraoka** [comment]
pls refer to #76
