### ISSUE TITLE
新しい投稿は上から表示されるようにしませんか？

### ISSUE THREAD

**Issue by LeonTeraoka** [LoL-pj/LoL-VC#74]
新規投稿を見るたびにスクロールしなきゃいけないじゃん！

**Comment by rutko** [comment]
現在は古い投稿が先頭にきている状態

影響する範囲
- TOPページの投稿一覧
- 検索結果の投稿一覧

この投稿一覧を作り出している箇所は以下である


TOPページ一覧
https://github.com/LoL-pj/LoL-VC/blob/5b208c8244bcda7fe6c87c1ca673e982021fb7ff/app/controllers/teams_controller.rb#L83

検索結果一覧
https://github.com/LoL-pj/LoL-VC/blob/5b208c8244bcda7fe6c87c1ca673e982021fb7ff/app/controllers/teams_controller.rb#L63


ヒント：railsの標準メソッドに並び替えができるメソッドがあるのでそれでidを指定する（╹◡╹）
