### ISSUE TITLE
TimeZone of Team model updated_at column to UTC

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#91]
## Summary

![スクリーンショット 2020-10-18 18 24 46](https://user-images.githubusercontent.com/26114407/96460939-beaa7500-125e-11eb-8216-5122118a6149.png)

## Final Status
Set the TimeZone of Team model updated_at column to JST

## FYI

**Comment by LeonTeraoka** [comment]
This is another format for the issues that we discussed today.
Looks good. pls let me use this for the next issue.

You have added the timezone of the Team model update_at column to JST.
Understood.
