### ISSUE TITLE
This  button doesn't look  well

### ISSUE THREAD

**Issue by rutko** [LoL-pj/LoL-VC#95]
## Summary
dont see too well this font color...😣😣
![スクリーンショット 2020-10-21 2 25 23](https://user-images.githubusercontent.com/26114407/96622652-2f2bc180-1345-11eb-9e80-fb3698ecfc28.png)

## Final Status
Change font color too user ability
## FYI

**Comment by LeonTeraoka** [comment]
I agree with you.
Please let me confirm this issue.
